SIM ?= icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell cat /home/saviour/study/fpga_spectrogram/src/module_list.txt)
# VERILOG_SOURCES = /home/saviour/study/fpga_spectrogram/src/videogen/pulse_detect_count.v
# TOPLEVEL = pulseDetectCount
# MODULE = tb_pulseDetectCount
COCOTB_LOG_LEVEL = TRACE

include $(shell cocotb-config --makefiles)/Makefile.sim